#!/usr/bin/env python3
"""
Figure 1: The Solar-Battery Integration Barrier

This script generates Figure 1 from the paper, comparing capacity trajectories
under exogenous vs endogenous learning assumptions.

Prerequisites:
    Run the main model first: python src/gb_electricity_model.py --mode normal
    This creates: gb_model_results.csv

Usage:
    python figures/figure1_integration_barrier.py

Output:
    figure1_integration_barrier.png
    figure1_integration_barrier.pdf
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

# Input file (generated by main model)
CSV_PATH = "gb_model_results.csv"

# Output paths
OUTPUT_PNG = "figure1_integration_barrier.png"
OUTPUT_PDF = "figure1_integration_barrier.pdf"

# Policy names (must match those in the CSV)
CURRENT_POLICY_NAME = "Current Policy"
RESCUE_POLICY_NAME = "Battery + Solar"

# Color scheme
COLORS = {
    'exogenous': '#2A9D8F',    # Teal
    'endogenous': '#E76F51',   # Coral
    'rescue': '#264653',       # Dark blue
}


# =============================================================================
# MAIN FIGURE CREATION
# =============================================================================

def create_figure1(df: pd.DataFrame) -> plt.Figure:
    """
    Create the four-panel Figure 1: Solar-Battery Integration Barrier.
    
    Panels:
        (a) Battery capacity trajectories
        (b) Solar PV capacity trajectories
        (c) Gas capacity trajectories (with lock-in shading)
        (d) Policy "rescue" scenario comparison
    
    Args:
        df: DataFrame with columns [period, learning_type, policy, 
            solar_gw, battery_gw, gas_gw, ...]
    
    Returns:
        matplotlib Figure object
    """
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    
    # Line style definitions
    exog_style = {
        'color': COLORS['exogenous'], 
        'linestyle': '--', 
        'linewidth': 2.5,
        'marker': 'o', 
        'markersize': 6
    }
    endog_style = {
        'color': COLORS['endogenous'], 
        'linestyle': '-', 
        'linewidth': 2.5,
        'marker': 's', 
        'markersize': 6
    }
    rescue_style = {
        'color': COLORS['rescue'], 
        'linestyle': '-', 
        'linewidth': 2.5,
        'marker': '^', 
        'markersize': 6
    }
    
    # Filter data for each scenario
    exog_data = df[
        (df['learning_type'] == 'exogenous') & 
        (df['policy'] == CURRENT_POLICY_NAME)
    ].sort_values('period')
    
    endog_data = df[
        (df['learning_type'] == 'endogenous') & 
        (df['policy'] == CURRENT_POLICY_NAME)
    ].sort_values('period')
    
    rescue_data = df[
        (df['learning_type'] == 'endogenous') & 
        (df['policy'] == RESCUE_POLICY_NAME)
    ].sort_values('period')
    
    print(f"Data points - Exogenous: {len(exog_data)}, "
          f"Endogenous: {len(endog_data)}, Rescue: {len(rescue_data)}")
    
    # =========================================================================
    # PANEL (a): Battery Capacity
    # =========================================================================
    ax1 = axes[0, 0]
    
    if len(exog_data) > 0:
        ax1.plot(exog_data['period'], exog_data['battery_gw'], 
                 **exog_style, label='Exogenous')
    if len(endog_data) > 0:
        ax1.plot(endog_data['period'], endog_data['battery_gw'], 
                 **endog_style, label='Endogenous')
    
    ax1.set_xlabel('Year', fontsize=11)
    ax1.set_ylabel('Battery capacity (GW)', fontsize=11)
    ax1.set_title('(a) Battery storage', fontsize=12, fontweight='bold')
    ax1.legend(loc='upper left', fontsize=10)
    ax1.set_ylim(bottom=0)
    ax1.grid(True, alpha=0.3)
    
    # =========================================================================
    # PANEL (b): Solar Capacity
    # =========================================================================
    ax2 = axes[0, 1]
    
    if len(exog_data) > 0:
        ax2.plot(exog_data['period'], exog_data['solar_gw'], 
                 **exog_style, label='Exogenous')
    if len(endog_data) > 0:
        ax2.plot(endog_data['period'], endog_data['solar_gw'], 
                 **endog_style, label='Endogenous')
    
    ax2.set_xlabel('Year', fontsize=11)
    ax2.set_ylabel('Solar PV capacity (GW)', fontsize=11)
    ax2.set_title('(b) Solar PV', fontsize=12, fontweight='bold')
    ax2.legend(loc='upper left', fontsize=10)
    ax2.set_ylim(bottom=0)
    ax2.grid(True, alpha=0.3)
    
    # =========================================================================
    # PANEL (c): Gas Capacity
    # =========================================================================
    ax3 = axes[1, 0]
    
    if len(exog_data) > 0:
        ax3.plot(exog_data['period'], exog_data['gas_gw'], 
                 **exog_style, label='Exogenous')
    if len(endog_data) > 0:
        ax3.plot(endog_data['period'], endog_data['gas_gw'], 
                 **endog_style, label='Endogenous')
        # Shade gas lock-in region
        ax3.fill_between(
            endog_data['period'], 
            endog_data['gas_gw'].min() * 0.95,
            endog_data['gas_gw'],
            alpha=0.2, 
            color=COLORS['endogenous'],
            label='Gas lock-in'
        )
    
    ax3.set_xlabel('Year', fontsize=11)
    ax3.set_ylabel('Gas capacity (GW)', fontsize=11)
    ax3.set_title('(c) Gas generation', fontsize=12, fontweight='bold')
    ax3.legend(loc='upper left', fontsize=10)
    ax3.set_ylim(bottom=0)
    ax3.grid(True, alpha=0.3)
    
    # =========================================================================
    # PANEL (d): Rescue Scenario
    # =========================================================================
    ax4 = axes[1, 1]
    
    if len(exog_data) > 0:
        ax4.plot(exog_data['period'], exog_data['battery_gw'], 
                 **exog_style, label='Exogenous')
    if len(endog_data) > 0:
        ax4.plot(endog_data['period'], endog_data['battery_gw'], 
                 **endog_style, label='Endogenous (no support)')
    if len(rescue_data) > 0:
        ax4.plot(rescue_data['period'], rescue_data['battery_gw'], 
                 **rescue_style, label='Endogenous + Battery subsidy')
        # Shade the rescue effect
        if len(endog_data) > 0:
            min_len = min(len(endog_data), len(rescue_data))
            ax4.fill_between(
                rescue_data['period'].values[:min_len], 
                endog_data['battery_gw'].values[:min_len],
                rescue_data['battery_gw'].values[:min_len],
                alpha=0.2, 
                color=COLORS['rescue']
            )
    
    ax4.set_xlabel('Year', fontsize=11)
    ax4.set_ylabel('Battery capacity (GW)', fontsize=11)
    ax4.set_title('(d) Policy "rescue" of endogenous pathway', 
                  fontsize=12, fontweight='bold')
    ax4.legend(loc='upper left', fontsize=9)
    ax4.set_ylim(bottom=0)
    ax4.grid(True, alpha=0.3)
    
    # =========================================================================
    # Finalize
    # =========================================================================
    plt.tight_layout()
    fig.suptitle('Figure 1: The Solar–Battery Integration Barrier', 
                 fontsize=14, fontweight='bold', y=1.02)
    
    return fig


def main():
    """Load data and generate Figure 1."""
    print("=" * 60)
    print("Generating Figure 1: Solar-Battery Integration Barrier")
    print("=" * 60)
    
    # Check for input file
    if not Path(CSV_PATH).exists():
        print(f"\nError: Input file not found: {CSV_PATH}")
        print("Please run the main model first:")
        print("  python src/gb_electricity_model.py --mode normal")
        return
    
    # Load data
    print(f"\nLoading data from: {CSV_PATH}")
    df = pd.read_csv(CSV_PATH)
    print(f"Loaded {len(df)} rows")
    print(f"Columns: {list(df.columns)}")
    print(f"Learning types: {df['learning_type'].unique()}")
    print(f"Policies: {df['policy'].unique()}")
    
    # Create figure
    fig = create_figure1(df)
    
    # Save outputs
    fig.savefig(OUTPUT_PNG, dpi=300, bbox_inches='tight', facecolor='white')
    fig.savefig(OUTPUT_PDF, bbox_inches='tight', facecolor='white')
    
    print(f"\nSaved: {OUTPUT_PNG}")
    print(f"Saved: {OUTPUT_PDF}")
    
    plt.show()


if __name__ == "__main__":
    main()
