#!/usr/bin/env python3
"""
Figure 2: Threshold Dynamics in Subsidy Effectiveness

This script generates Figure 2 from the paper, showing the sharp threshold
behavior in battery subsidies and the efficiency gains from coordinated
solar-battery subsidies.

Prerequisites:
    Run the subsidy sweeps first:
        python src/gb_electricity_model.py --mode battery_sweep
        python src/gb_electricity_model.py --mode solar_battery_sweep
    
    This creates:
        battery_subsidy_sweep_endogenous.csv
        solar_battery_subsidy_grid_endogenous.csv

Usage:
    python figures/figure2_threshold_dynamics.py

Output:
    figure2_threshold_dynamics.png
    figure2_threshold_dynamics.pdf
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

# Input files (generated by subsidy sweeps)
BATTERY_SWEEP_CSV = "battery_subsidy_sweep_endogenous.csv"
SOLAR_BATTERY_GRID_CSV = "solar_battery_subsidy_grid_endogenous.csv"

# Output paths
OUTPUT_PNG = "figure2_threshold_dynamics.png"
OUTPUT_PDF = "figure2_threshold_dynamics.pdf"

# Color scheme
COLORS = {
    'threshold': '#E63946',    # Red - threshold region
    'deploy': '#2A9D8F',       # Teal - high deployment
    'low': '#F4A261',          # Orange - low deployment
}


# =============================================================================
# DATA LOADING
# =============================================================================

def load_and_clean_data():
    """Load and clean the sweep CSV files."""
    
    # Load battery sweep
    battery_df = pd.read_csv(BATTERY_SWEEP_CSV)
    battery_df.columns = battery_df.columns.str.strip()
    
    # Load grid
    grid_df = pd.read_csv(SOLAR_BATTERY_GRID_CSV)
    grid_df.columns = grid_df.columns.str.strip()
    
    # Fix any mangled column names
    grid_df.columns = [col.replace('n    ', '').replace('n\t', '') 
                       for col in grid_df.columns]
    
    return battery_df, grid_df


# =============================================================================
# MAIN FIGURE CREATION
# =============================================================================

def create_figure2(battery_df: pd.DataFrame, grid_df: pd.DataFrame) -> plt.Figure:
    """
    Create the three-panel Figure 2: Threshold Dynamics.
    
    Panels:
        (a) Battery capacity vs battery-only subsidy (threshold identification)
        (b) 2D policy surface (solar × battery heatmap with zero gas contour)
        (c) Cost comparison: battery-only vs coordinated
    
    Success criterion: Zero gas growth (gas_growth_gw <= 0)
    
    Args:
        battery_df: DataFrame from battery-only sweep
        grid_df: DataFrame from solar-battery grid search
    
    Returns:
        matplotlib Figure object
    """
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # =========================================================================
    # PANEL (a): Battery capacity vs battery-only subsidy
    # =========================================================================
    ax1 = axes[0]
    
    x = battery_df['initial_subsidy_per_kw']
    y = battery_df['battery_end_gw']
    gas_growth = battery_df['gas_growth_gw']
    
    ax1.plot(x, y, 'o-', color=COLORS['deploy'], linewidth=2, markersize=6)
    
    # Find threshold: first subsidy level where gas_growth <= 0
    zero_gas_mask = gas_growth <= 0
    if zero_gas_mask.any():
        threshold_subsidy = x[zero_gas_mask].min()
        below_threshold = x[x < threshold_subsidy].max()
        
        # Shade threshold region
        ax1.axvspan(
            below_threshold, threshold_subsidy, 
            alpha=0.3, 
            color=COLORS['threshold'],
            label=f'Threshold region\n(£{below_threshold:.0f}–{threshold_subsidy:.0f}/kW)'
        )
        
        # Mark threshold capacity
        threshold_battery = battery_df[
            battery_df['initial_subsidy_per_kw'] == threshold_subsidy
        ]['battery_end_gw'].values[0]
        ax1.axhline(y=threshold_battery, color=COLORS['threshold'], 
                    linestyle=':', alpha=0.5)
        ax1.text(
            x.max() - 2, threshold_battery + 30, 
            f'{threshold_battery:.0f} GW\n(zero gas growth)', 
            fontsize=9, ha='right', color=COLORS['threshold']
        )
    
    # Annotations
    ax1.annotate('Below threshold:\ngas still growing', 
                 xy=(x.min() + 3, 20), fontsize=9, ha='left')
    ax1.annotate('Above threshold:\nzero gas growth', 
                 xy=(x.max() - 3, y.max() - 100), fontsize=9, ha='right')
    
    ax1.set_xlabel('Battery subsidy (£/kW)', fontsize=11)
    ax1.set_ylabel('Battery capacity in 2049 (GW)', fontsize=11)
    ax1.set_title('(a) Battery-only subsidy threshold', fontsize=12, fontweight='bold')
    ax1.legend(loc='upper left', fontsize=9)
    ax1.set_ylim(bottom=0)
    ax1.grid(True, alpha=0.3)
    
    # =========================================================================
    # PANEL (b): 2D policy surface (solar × battery heatmap)
    # =========================================================================
    ax2 = axes[1]
    
    # Pivot data for heatmap - show battery growth
    pivot_battery = grid_df.pivot(
        index='solar_initial', 
        columns='battery_initial', 
        values='battery_growth_gw'
    )
    
    # Also pivot gas growth for contour line
    pivot_gas = grid_df.pivot(
        index='solar_initial', 
        columns='battery_initial', 
        values='gas_growth_gw'
    )
    
    # Custom colormap: orange (low) -> white -> teal (high)
    cmap = LinearSegmentedColormap.from_list(
        'battery_growth', 
        [COLORS['low'], '#FFFFFF', COLORS['deploy']]
    )
    
    # Plot heatmap
    im = ax2.imshow(
        pivot_battery.values, 
        cmap=cmap, 
        aspect='auto', 
        origin='lower',
        extent=[
            pivot_battery.columns.min(), pivot_battery.columns.max(),
            pivot_battery.index.min(), pivot_battery.index.max()
        ]
    )
    
    # Add contour line at gas_growth = 0 (critical boundary)
    X, Y = np.meshgrid(pivot_gas.columns, pivot_gas.index)
    try:
        contour = ax2.contour(
            X, Y, pivot_gas.values, 
            levels=[0], 
            colors=[COLORS['threshold']], 
            linewidths=2.5, 
            linestyles='-'
        )
        ax2.clabel(contour, fmt='0 GW\ngas growth', fontsize=8)
    except Exception:
        pass  # Contour may fail if no zero crossing
    
    # Mark most efficient point: minimum total subsidy with gas_growth <= 0
    successful = grid_df[grid_df['gas_growth_gw'] <= 0].copy()
    if len(successful) > 0:
        successful['total_sub'] = successful['battery_initial'] + successful['solar_initial']
        best = successful.loc[successful['total_sub'].idxmin()]
        ax2.plot(
            best['battery_initial'], best['solar_initial'], 
            '*', color='white', markersize=18, 
            markeredgecolor='black', markeredgewidth=2
        )
        ax2.annotate(
            f"£{int(best['battery_initial'])} + £{int(best['solar_initial'])}\n(min cost)", 
            xy=(best['battery_initial'], best['solar_initial']),
            xytext=(-50, 15), textcoords='offset points', fontsize=9,
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.9),
            arrowprops=dict(arrowstyle='->', color='black')
        )
        
        print(f"\nMost efficient coordinated point (zero gas growth):")
        print(f"  Battery: £{best['battery_initial']:.0f}/kW")
        print(f"  Solar: £{best['solar_initial']:.0f}/kW")
        print(f"  Total subsidy cost: £{best['total_subsidy_cost_bn']:.1f}bn")
    
    plt.colorbar(im, ax=ax2, label='Battery capacity growth (GW)')
    
    ax2.set_xlabel('Battery subsidy (£/kW)', fontsize=11)
    ax2.set_ylabel('Solar subsidy (£/kW)', fontsize=11)
    ax2.set_title('(b) Coordinated subsidy surface', fontsize=12, fontweight='bold')
    
    # Region labels
    ax2.text(
        pivot_battery.columns.min() + 2, pivot_battery.index.max() - 2, 
        'Low battery\ndeployment', fontsize=9, ha='left', va='top', 
        color='#E76F51', fontweight='bold'
    )
    ax2.text(
        pivot_battery.columns.max() - 2, pivot_battery.index.min() + 2, 
        'High battery\ndeployment', fontsize=9, ha='right', va='bottom', 
        color=COLORS['deploy'], fontweight='bold'
    )
    
    # =========================================================================
    # PANEL (c): Cost comparison
    # =========================================================================
    ax3 = axes[2]
    
    # Battery-only: minimum subsidy to reach zero gas growth
    bat_zero_gas = battery_df[battery_df['gas_growth_gw'] <= 0]
    if len(bat_zero_gas) > 0:
        bat_only_row = bat_zero_gas.iloc[0]
        bat_only_cost = bat_only_row['total_subsidy_cost_bn']
        bat_only_sub = bat_only_row['initial_subsidy_per_kw']
        print(f"\nBattery-only threshold (zero gas growth):")
        print(f"  Subsidy: £{bat_only_sub:.0f}/kW")
        print(f"  Total cost: £{bat_only_cost:.1f}bn")
    else:
        print("WARNING: No battery-only scenario achieves zero gas growth!")
        bat_only_row = battery_df.iloc[-1]
        bat_only_cost = bat_only_row['total_subsidy_cost_bn']
        bat_only_sub = bat_only_row['initial_subsidy_per_kw']
    
    # Coordinated: minimum COST to reach zero gas growth
    if len(successful) > 0:
        coord_row = successful.loc[successful['total_subsidy_cost_bn'].idxmin()]
        coord_cost = coord_row['total_subsidy_cost_bn']
        print(f"\nCoordinated minimum cost (zero gas growth):")
        print(f"  Battery: £{coord_row['battery_initial']:.0f}/kW")
        print(f"  Solar: £{coord_row['solar_initial']:.0f}/kW")
        print(f"  Total cost: £{coord_cost:.1f}bn")
    else:
        print("WARNING: No coordinated scenario achieves zero gas growth!")
        coord_row = grid_df.loc[grid_df['total_subsidy_cost_bn'].idxmin()]
        coord_cost = coord_row['total_subsidy_cost_bn']
    
    # Bar chart
    categories = ['Battery-only', 'Coordinated\n(Solar + Battery)']
    costs = [bat_only_cost, coord_cost]
    colors_bar = [COLORS['low'], COLORS['deploy']]
    
    bars = ax3.bar(categories, costs, color=colors_bar, 
                   edgecolor='black', linewidth=1.5)
    
    # Cost ratio annotation
    if bat_only_cost > 0 and coord_cost > 0:
        ratio = coord_cost / bat_only_cost
        savings = (1 - ratio) * 100
        ax3.annotate(
            f'{ratio:.0%} of\nbattery-only\n({savings:.0f}% savings)', 
            xy=(1, coord_cost), 
            xytext=(0, 15), textcoords='offset points',
            ha='center', fontsize=10, fontweight='bold'
        )
    
    # Subsidy levels on bars
    ax3.text(
        0, bat_only_cost / 2, 
        f'£{bat_only_sub:.0f}/kW\nbattery only', 
        ha='center', va='center', fontsize=9, 
        color='white', fontweight='bold'
    )
    ax3.text(
        1, coord_cost / 2, 
        f"£{int(coord_row['battery_initial'])} bat\n£{int(coord_row['solar_initial'])} sol", 
        ha='center', va='center', fontsize=9, 
        color='white', fontweight='bold'
    )
    
    ax3.set_ylabel('Total subsidy expenditure (£ billion)', fontsize=11)
    ax3.set_title('(c) Cost to achieve zero gas growth', fontsize=12, fontweight='bold')
    ax3.set_ylim(bottom=0)
    ax3.grid(True, alpha=0.3, axis='y')
    
    # =========================================================================
    # Finalize
    # =========================================================================
    plt.tight_layout()
    
    return fig


def main():
    """Load data and generate Figure 2."""
    print("=" * 60)
    print("Generating Figure 2: Threshold Dynamics")
    print("=" * 60)
    
    # Check for input files
    missing_files = []
    if not Path(BATTERY_SWEEP_CSV).exists():
        missing_files.append(BATTERY_SWEEP_CSV)
    if not Path(SOLAR_BATTERY_GRID_CSV).exists():
        missing_files.append(SOLAR_BATTERY_GRID_CSV)
    
    if missing_files:
        print(f"\nError: Input files not found:")
        for f in missing_files:
            print(f"  - {f}")
        print("\nPlease run the subsidy sweeps first:")
        print("  python src/gb_electricity_model.py --mode battery_sweep")
        print("  python src/gb_electricity_model.py --mode solar_battery_sweep")
        return
    
    # Load data
    print("\nLoading data...")
    battery_df, grid_df = load_and_clean_data()
    
    print(f"\nBattery sweep: {len(battery_df)} rows")
    print(f"  Subsidy range: £{battery_df['initial_subsidy_per_kw'].min():.0f} – "
          f"£{battery_df['initial_subsidy_per_kw'].max():.0f}/kW")
    print(f"  Gas growth range: {battery_df['gas_growth_gw'].min():.1f} – "
          f"{battery_df['gas_growth_gw'].max():.1f} GW")
    
    print(f"\nSolar-battery grid: {len(grid_df)} rows")
    print(f"  Battery range: £{grid_df['battery_initial'].min():.0f} – "
          f"£{grid_df['battery_initial'].max():.0f}/kW")
    print(f"  Solar range: £{grid_df['solar_initial'].min():.0f} – "
          f"£{grid_df['solar_initial'].max():.0f}/kW")
    
    # Count successful scenarios
    bat_zero = (battery_df['gas_growth_gw'] <= 0).sum()
    grid_zero = (grid_df['gas_growth_gw'] <= 0).sum()
    print(f"\nScenarios achieving zero gas growth:")
    print(f"  Battery-only: {bat_zero}/{len(battery_df)}")
    print(f"  Coordinated: {grid_zero}/{len(grid_df)}")
    
    # Create figure
    print(f"\n{'=' * 60}")
    print("Creating Figure 2...")
    print(f"{'=' * 60}")
    
    fig = create_figure2(battery_df, grid_df)
    
    # Save outputs
    fig.savefig(OUTPUT_PNG, dpi=300, bbox_inches='tight', facecolor='white')
    fig.savefig(OUTPUT_PDF, bbox_inches='tight', facecolor='white')
    
    print(f"\nSaved: {OUTPUT_PNG}")
    print(f"Saved: {OUTPUT_PDF}")
    
    plt.show()


if __name__ == "__main__":
    main()
